[20791] Architecture update
eProsima/SustainML pull request #27
Opened 2024-04-15 14:10 UTC by JesusPoderoso

This PR updates the SustainML node library based on the latest design update.
It also fixes the types regeneration script, and adds some instructions to do that task.

**IMPORTANT**: tests have not been fixed, so most of them will fail.

2024-04-16 08:34 UTC, Mario-DL requested changes
Nice upgrade refactor.
Apart from the already mentioned changes:
* Pass the name in the `prepare_new_entry` 
* Resolve some states issue with the new nodes
* Work on an intermediate branch

I am leaving some minor suggestions. Also, I am missing the change on the `on_new_node_output` OrchestratorNodeHandle API to incorporate the new `TaskId` argument (it would pass 3: TaskId, NodeId, data, see design). 

In the next PR I will fix the failing tests and will also try to at least prepare the infrastructure to handle multiple iterations, adding the `/baseline` topics (in another third PR)

2024-04-16 08:34 UTC, Mario-DL commented on sustainml_cpp/examples/CliModules/main.cpp
>          ui.task_id(task_id);
Here we may want to fill a task_name including the `to_string(task_id)` within the name, to make it change across tasks

2024-04-16 08:34 UTC, Mario-DL commented on sustainml_cpp/include/sustainml_cpp/nodes/MLModelMetadataNode.hpp
> +namespace ml_model_metadata_module {
We may consider using the same namespace as for the MLModelNode, the `::ml_model_provider` as both of them are related

2024-04-16 08:34 UTC, Mario-DL commented on sustainml_cpp/include/sustainml_cpp/nodes/HardwareConstraintsNode.hpp
> +namespace hw_constraints_module {
We may think of using the same namespace as for the hwResourcesNode, the `hw_module`

2024-04-18 07:07 UTC, Mario-DL commented
> Nice upgrade refactor. Apart from the already mentioned changes:
> 
> * Pass the name in the `prepare_new_entry`
> * Resolve some states issue with the new nodes
> * Work on an intermediate branch
> 
> I am leaving some minor suggestions. Also, I am missing the change on the `on_new_node_output` OrchestratorNodeHandle API to incorporate the new `TaskId` argument (it would pass 3: TaskId, NodeId, data, see design).
> 
> In the next PR I will fix the failing tests and will also try to at least prepare the infrastructure to handle multiple iterations, adding the `/baseline` topics (in another third PR)

My previous comment on the `on_new_node_output` was discarded as the TaskId information can be found within the data message itself as it now travels with it

2024-04-18 13:42 UTC, JesusPoderoso commented
Thanks @Mario-DL!!
Commits [c508c4f](https://github.com/eProsima/SustainML/pull/27/commits/c508c4fd2c2123d4435bbd6bcf0df06be80b4cc4), [7de2021](https://github.com/eProsima/SustainML/pull/27/commits/7de20210653cb9c497a683b009996480891fa4a6), [7ff5b29](https://github.com/eProsima/SustainML/pull/27/commits/7ff5b2960fa699d8a92a0310be7d6ba26b784286), [4727d91](https://github.com/eProsima/SustainML/pull/27/commits/4727d9199333fe02f9e5d7848173480af93c6125) LGTM

2024-04-18 13:45 UTC, merged