[20791] Feature: Baseline topics
eProsima/SustainML pull request #29
Opened 2024-04-22 15:33 UTC by Mario-DL

This PR brings the `baseline topics` feature corresponding to the update v2 of the design

2024-04-23 05:41 UTC, Mario-DL commented
Im going to try hardening the python modules python test that sometimes fail.

2024-04-24 07:25 UTC, JesusPoderoso requested changes

2024-04-24 07:25 UTC, JesusPoderoso commented on sustainml_cpp/src/cpp/orchestrator/ModuleNodeProxy.cpp
> +#include "ModuleNodeProxy.ipp"
EOF

2024-04-24 07:41 UTC, JesusPoderoso approved these changes
LGTM

2024-04-24 09:51 UTC, JesusPoderoso approved these changes
LGTM

2024-04-24 09:51 UTC, merged